name: Schedule pipeline

on:
  schedule:
    - cron: 30 00 * * 2-6
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collections
        run: newman run "Mike Trello.postman_collection.json" -e "Trello.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export Report.html
