name: Scheduled Run

on:
 workflow_dispatch:
 schedule:
    - cron: 30 00 * * 2-6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo, so the job can access it.
      - uses: actions/checkout@v4

      # Install Node on the runner
      - name: Use Node.js
        uses: actions/setup-node@v3

      # Install newman globally, and install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run postman collection
      - name: Run Postman Collection and Generate HTML Report
        run: 'newman run Trello.postman_collection.json -e "Trello.postman_environment.json" --reporters cli,htmlextra --reporter-htmlextra-export report.html'

      - name: Publish test run results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report.html
          path: "*html"

      - name: Send mail with report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: mike.nekrasov82@gmail.com
          subject: Test Report
          from: GitHub Actions <actions@example.com>
          attachments: report.html
